### ISSUE TITLE
filter_artifacts gives 502 error when returning whole collection

### ISSUE THREAD

**Issue by dtomassi** [BugSwarm/common#22]
# Problem
Trying to get both unreproducible and reproducible artifacts gives a 502 error.

Example:
```
>>> from bugswarm.common.rest_api.database_api import DatabaseAPI
>>> from bugswarm.private import credentials
>>> bugswarmapi = DatabaseAPI(token=credentials.DATABASE_PIPELINE_TOKEN)
>>> bugswarmapi.filter_artifacts('{}')
http://www.api.bugswarm.org/v1/artifacts?where=%7B%7D
b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dtomassi/bugswarm/common/bugswarm/common/rest_api/database_api.py", line 89, in filter_artifacts
    return self._filter(DatabaseAPI._artifacts_endpoint(), api_filter)
  File "/home/dtomassi/bugswarm/common/bugswarm/common/rest_api/database_api.py", line 606, in _filter
    return self._iter_pages(url)
  File "/home/dtomassi/bugswarm/common/bugswarm/common/rest_api/database_api.py", line 573, in _iter_pages
    next_resp.raise_for_status()
  File "/home/dtomassi/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://www.api.bugswarm.org/v1/artifacts?where=%7B%7D
```

**Comment by crubiog** [comment]
@aTonyXiao Can you replicate this bug?

**Comment by aTonyXiao** [comment]
## Some clue
we noticed `[CRITICAL] WORKER TIMEOUT` appears in `gunicorn.log` whenever the error occurs. 
It because we turned off the pagination in https://github.com/BugSwarm/database/pull/29. Now when the API will timeout when return large document.

## Fixes:
Two routes:
1. change the timeout setting in `gunicorn` ( also `nginx`? maybe), so the API have longer time to process.
1. restore the pagination and set a proper page size

I think 2 is more desirable. What do you think? @crubiog  @dtomassi
